justin_laureano/urls.py
from django.urls import path
from . import views

app_name = 'justin_laureano'

# /justin_laureano/
urlpatterns = [
    path('', views.home_page, name='home'),
    path('project_1/', views.the_gathering, name='project_1'),
    path('project_2/', views.news, name='project_2'),
    path('project_3/', views.trivia, name='project_3'),
    path('project_4/', views.design, name='project_4'),
    path('project_5/', views.recipe_box, name='project_5'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

# /news/
urlpatterns = [
    path('', views.home_page, name='home'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('justin_laureano.urls'), name='Justin_laureano'),
    path('', include('recipe_box.urls'), name='recipe_box'),
    path('the_gathering/', include('the_gathering.urls'), name='gathering'),
    path('trivia/', include('trivia.urls'), name='trivia'),
    path('news/', include('news.urls'), name='news'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_box/urls.py
from django.urls import path
from . import views

app_name = 'recipe_box'

# /justin_laureano/
urlpatterns = [
    path('', views.home_page, name='home')
]

the_gathering/urls.py
from django.urls import path
from . import views

app_name = 'the_gathering'

# /the_gathering/
urlpatterns = [
    path('', views.home_page, name='home'),
    path('eat/', views.eat_page, name='eat'),
    path('drink/', views.drink_page, name='drink'),
    path('shop/', views.shop_page, name='shop'),
    path('events/', views.events_page, name='events'),
    path('about/', views.about_page, name='about'),
    path('menus/', views.menus_page, name='menus'),
    path('private_events/', views.private_events_page, name='private_events'),
    path('reservations/', views.reservations_page, name='reservations'),
    path('contact/', views.contact_page, name='contact'),
]

trivia/urls.py
from django.urls import path
from . import views

app_name = 'trivia'

# /trivia/
urlpatterns = [
    path('', views.home_page, name='home'),
]

justin_laureano/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

recipe_box/models.py
from django.db import models

# Create your models here.

the_gathering/models.py
from django.db import models


class LunchMenu(models.Model):
    LUNCH_TYPE = (
        ('Lunch Soups', 'Lunch Soups'),
        ('Lunch Salads', 'Lunch Salads'),
        ('Lunch Fare', 'Lunch Fare'),
        ('Lunch Sides', 'Lunch Sides'),
        ('Lunch Sweets', 'Lunch Sweets')
    )

    type = models.CharField(max_length=50, choices=LUNCH_TYPE, blank=True)
    item = models.CharField(max_length=120)
    description = models.TextField(max_length=800, blank=True)
    price = models.CharField(max_length=15, blank=True)
    add_on = models.TextField(max_length=120, blank=True)
    add_on_price = models.CharField(max_length=120, blank=True)

    def __str__(self):
        return self.item


class DinnerMenu(models.Model):
    DINNER_TYPE = (
        ('Appetizers', 'Appetizers'),
        ('Petite Salads', 'Petite Salads'),
        ('Entrees', 'Entrees'),
        ('A la Carte', 'A la Carte'),
        ('Desserts', 'Desserts')
    )

    type = models.CharField(max_length=50, choices=DINNER_TYPE, blank=True)
    item = models.CharField(max_length=120)
    description = models.TextField(max_length=800, blank=True)
    price = models.CharField(max_length=15, blank=True)
    add_on = models.TextField(max_length=120, blank=True)
    add_on_price = models.CharField(max_length=120, blank=True)

    def __str__(self):
        return self.item


class WineMenu(models.Model):
    WINE_TYPE = (
        ('Food', 'Food'),
        ('Red Wine', 'Red Wine'),
        ('White Wine', 'White Wine')
    )

    type = models.CharField(max_length=50, choices=WINE_TYPE, blank=True)
    item = models.CharField(max_length=120)
    description = models.TextField(max_length=800, blank=True)
    taste_price = models.CharField(max_length=15, blank=True)
    glass_price = models.CharField(max_length=15, blank=True)
    bottle_price = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.item


class AnvilMenu(models.Model):
    ANVIL_TYPE = (
        ('Food', 'Food'),
        ('Kentucky Straight Bourbon', 'Kentucky Straight Bourbon'),
        ('Bourbon Whiskey, Blends, Irish, Miscreants',
         'Bourbon Whiskey, Blends, Irish, Miscreants'),
        ('Rye Whiskey', 'Rye Whiskey'),
        ('Single Malt Scotch Whisky', 'Single Malt Scotch Whisky'),
        ('Blended Scotch Whisky', 'Blended Scotch Whisky'),
        ('The Elite', 'The Elite')
    )

    type = models.CharField(max_length=50, choices=ANVIL_TYPE, blank=True)
    item = models.CharField(max_length=120)
    description = models.TextField(max_length=800, blank=True)
    price = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.item


class LiveEvent(models.Model):
    VENUE = (
        ('The Gathering', 'The Gathering'),
        ('The Gathering Wine', 'The Gathering Wine'),
        ('The Anvil', 'The Anvil'),
        ('The Courtyard Patio', 'The Courtyard Patio')
    )

    event_name = models.CharField(max_length=100)
    event_date = models.CharField(max_length=120)
    event_time = models.CharField(max_length=120)
    event_venue = models.CharField(max_length=30, choices=VENUE, blank=True)
    event_description = models.TextField(max_length=800, blank=True)
    event_image = models.ImageField(upload_to='static/image/live_events/',
                                    default='static/images/logo.png')

    def __str__(self):
        return self.event_name

justin_laureano/views.py
from django.shortcuts import render
# from .models import Project


def home_page(request):
    return render(request, 'justin_laureano/index.html', {})

def recipe_box(request):
    return render(request, 'justin_laureano/recipe_box.html', {})

def the_gathering(request):
    return render(request, 'justin_laureano/the_gathering.html', {})

def news(request):
    return render(request, 'justin_laureano/news.html', {})

def trivia(request):
    return render(request, 'justin_laureano/trivia.html', {})

def design(request):
    return render(request, 'justin_laureano/design.html', {})

news/views.py
from django.shortcuts import render
# from .models import Project

def home_page(request):
    return render(request, 'news/index.html', {})

recipe_box/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'recipe_box/index.html', {})

the_gathering/views.py
from django.shortcuts import render
from .models import LunchMenu, DinnerMenu, WineMenu, AnvilMenu, LiveEvent


def home_page(request):
        return render(request, 'the_gathering/index.html', {})


def eat_page(request):
    return render(request, 'the_gathering/eat.html', {})


def drink_page(request):
    return render(request, 'the_gathering/drink.html', {})


def shop_page(request):
    return render(request, 'the_gathering/shop.html', {})


def events_page(request):
    live_event = LiveEvent.objects.all()
    return render(request, 'the_gathering/events.html', {'live_event':
                                                        live_event})


def about_page(request):
    return render(request, 'the_gathering/about.html', {})


def menus_page(request):
    lunch_menu = LunchMenu.objects.all()
    dinner_menu = DinnerMenu.objects.all()
    wine_menu = WineMenu.objects.all()
    anvil_menu = AnvilMenu.objects.all()

    content = {'lunch_menu': lunch_menu, 'dinner_menu': dinner_menu,
               'wine_menu': wine_menu, 'anvil_menu': anvil_menu}
    return render(request, 'the_gathering/menus.html', content)


def private_events_page(request):
    return render(request, 'the_gathering/private_events.html', {})


def reservations_page(request):
    return render(request, 'the_gathering/reservations.html', {})


def contact_page(request):
    return render(request, 'the_gathering/contact.html', {})

trivia/views.py
from django.shortcuts import render
# from .models import Project

def home_page(request):
    return render(request, 'trivia/index.html', {})

justin_laureano/templates/justin_laureano/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Justin Laureano's Web Portfolio</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <!-- Bootstrap CSS CDN -->
    <link rel="shortcut icon" href="{% static 'favicon/favicon.png' %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display+SC:400,400i,900|Roboto:300,400,500,700|Crimson+Text:400,600|Work+Sans:400,600|Montserrat:400|Lemonada|Stardos+Stencil:700|Oswald:700|Droid+Serif:400|Open+Sans|PT+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main_style.css' %}">
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
</head>
<body>
    <nav class="main-nav">
        <div class="row text-center">
            <div class="col-12 fixed-top">
                <span class="close-btn"><i class="fas fa-times fa-2x close-btn"></i></span>
            </div>
            <div class="col-12">
                <ul class="list-unstyled h3">
                    <a href="{% url 'justin_laureano:home' %}"><li class="my-2">Home</li></a>
                    <a href="{% url 'justin_laureano:project_1' %}"><li class="my-2">The Gathering</li></a>
                    <a href="{% url 'justin_laureano:project_2' %}"><li class="my-2">News &amp; Photo Viewer</li></a>
                    <a href="{% url 'justin_laureano:project_3' %}"><li class="my-2">Trivia Game</li></a>
                    <a href="{% url 'justin_laureano:project_4' %}"><li class="my-2">Graphic Design Gallery</li></a>
                    <a href="{% url 'justin_laureano:home' %}#space-skills" class="close-btn"><li class="my-2">Skills</li></a>
                    <a href="{% url 'justin_laureano:home' %}#space-about" class="close-btn"><li class="my-2">About Me</li></a>
                </ul>
            </div>
            <div class="col-12">
                <ul class="list-inline">
                    <a href="">
                        <li class="list-inline-item">
                            <i class="fab fa-github"></i>
                        </li>
                    </a>
                </ul>
            </div>
        </div>

    </nav>
    <div class="bg-overlay"></div>
    <div class="container-fluid" id="top">

        {% block content %}
        {% endblock %}

        <footer>
            <div class="row">
                <div class="col-12 text-center gray">
                    <a href="#top" class="scroll-top-btn">
                        <i class="fas fa-chevron-up fa-lg"></i>
                        <p>Go To Top</p>
                    </a>
                    <div class="triangle-top"></div>
                </div>
            </div>
        </footer>

    </div> <!--End Container -->

    <script src="{% static 'js/sr.js' %}"></script>
    <!-- jQuery CDN -->
    <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <!-- Bootstrap Js CDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="{% static 'js/main_function.js' %}"></script>
</body>
</html>

justin_laureano/templates/justin_laureano/news.html
{% extends 'justin_laureano/base.html' %}
{% load staticfiles %}
{% block content %}

<header class="row">
    <div class="header-static col-12 py-3">
        <div class="logo-sm">
            <img src="{% static 'images/portfolio/logo.svg' %}" class="logo-img-sm" alt="Justin Laureano" height="25px">
            <div class="diamond-sm"></div>
        </div>
    </div>
</header>

<div class="row project-landing">
    <div class="col-10 col-sm-3 offset-1 align-self-center pl-0">
        <h1 class="text-nowrap sr-intro-sequence">News &<br>Photo Viewer</h1>
        <p class="gray detail py-2 sr-intro-sequence">
            Featuring a magazine styled layout, this custom designed photo and newsfeed website keeps me in the know and entertained with no distractions.
        </p>
        <a href="{% url 'news:home' %}" class="view-btn my-3 py-2 px-4 text-center view-btn" target="blank">Visit Site</a>
    </div>
    <div class="col-12 col-sm-8 mt-5 mt-sm-0 sr-laptop-right">
        <img src="{% static 'images/news/news_home_laptop.png' %}" class="news-home-laptop" alt="News &amp; Photo Viewer Laptop View" class="img-fluid">
    </div>
</div>
<div class="row my-5">
    <div class="col-10 col-sm-5 offset-1 overflow-hidden">
        <p class="text-uppercase font-weight-bold sr-intro-sequence">Identity</p>
        <p class="gray sr-intro-sequence">
            With so many news sites feeling cluttered and overwhelming, I wanted to create a contrasting user experience with a minimal layout focusing only on the necessary information.
        </p>
    </div>
    <div class="col-10 offset-1 col-sm-5 offset-sm-0 overflow-hidden">
            <p class="text-uppercase font-weight-bold sr-intro-sequence">Specs</p>
            <p class="gray sr-intro-sequence">
                The website is styled using modern HTML and CSS practices so that the experience is pleasant on all devices. Javascript and jQuery were used to retreive data using popular API'S.
            </p>
        </div>
</div>
<div class="row justify-content-center project-showcase" id="news-project-showcase">
    <div class="col-12 col-sm-8 text-center showcase-item">
        <img src="{% static 'images/news/news_photo_showcase.png' %}" alt="News &amp; Photo Viewer Tablet &amp; Phone View" class="img-fluid showcase-img">
    </div>
    <div class="col-12 col-sm-8 text-center showcase-item">
        <img src="{% static 'images/news/news_newsfeed_showcase.png' %}" alt="News &amp; Photo Viewer Tablet &amp; Phone View" class="img-fluid showcase-img">
    </div>
    <div class="col-12 col-sm-8 text-center showcase-item">
        <img src="{% static 'images/news/news_frontpage_showcase.png' %}" alt="News &amp; Photo Viewer Tablet &amp; Phone View" class="img-fluid showcase-img">
    </div>
</div>
<div class="row font-showcase" id="news-font-showcase">
    <div class="col-12 offset-sm-1 mt-3 mt-sm-0">
        <p class="text-uppercase font-weight-bold gray mb-1 sr-font-sequence">Heading</p>
        <p class="text-uppercase font-weight-bold h3 tnr sr-font-sequence">Times New Roman</p>
        <p class="text-uppercase gray tnr mb-5 sr-font-sequence">abcdefghijklmnopqrstuvwxyz</p>
    </div>
    <div class="col-12 col-sm-7 offset-sm-1">
            <p class="text-uppercase font-weight-bold gray mb-1 sr-font-sequence">Body</p>
            <p class="text-uppercase font-weight-bold h5 work-sans sr-font-sequence">Montserrat</p>
            <p class="text-uppercase gray montserrat mb-0 sr-font-sequence">abcdefghijklmnopqrstuvwxyz</p>
            <p class="text-lowercase gray montserrat sr-font-sequence">abcdefghijklmnopqrstuvwxyz</p>
            <p class="text-lowercase gray montserrat sr-font-sequence">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus natus magni, sint praesentium assumenda corporis eaque impedit esse qui ut.</p>
        </div>
</div>
<div class="row mb-5">
    <div class="col-12 col-sm-11 offset-sm-1 overflow-hidden">
        <a href="{% url 'justin_laureano:project_3' %}"><h5 class="ml-3 mb-5 sr-font-sequence">Next: Trivia Game</h5></a>
    </div>
</div>
{% endblock %}

recipe_box/templates/recipe_box/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Recipe Box</title>
    {% load staticfiles %}

</head>
<body> 

</body>
</html>

the_gathering/templates/the_gathering/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>The Gathering</title>
        <!-- Loads the path to your static files -->
        {% load staticfiles %}
        <!-- Bootstrap CSS CDN -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- Our Custom CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
        <!-- Scroll Reveal -->
        <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>

    </head>
    <body>

        <div class="wrapper">
            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div id="dismiss">
                    <i class="fa fa-align-justify fa-sm" aria-hidden="true"></i>
                </div>

                <div class="sidebar-header">
                </div>

                <ul class="list-unstyled components">

                    <li>
                        <a href="{% url 'the_gathering:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:eat' %}">Eat</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:drink' %}">Drink</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:shop' %}">Shop</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:events' %}">Events</a>
                    </li>
                    <li>
                        <hr/>
                    </li>

                    <li>
                        <a href="{% url 'the_gathering:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:menus' %}">Menus</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:private_events' %}">Private Events</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:reservations' %}">Reservation</a>
                    </li>
                    <li>
                        <a href="{% url 'the_gathering:contact' %}">Contact</a>
                    </li>
                    <li>
                        <ul class="list-inline justify-content-left">

                            <li class="list-inline-item cat-item">
                                <a href="https://www.instagram.com/thegatheringfindlay/" class="social" target="_blank">
                                    <i class="fa fa-instagram fa-lg" aria-hidden="true"></i>
                                </a>
                            </li>
                            <li class="list-inline-item cat-item">
                                <a href="https://www.facebook.com/FindlayGathering/" class="social" target="_blank">
                                    <i class="fa fa-facebook fa-lg" aria-hidden="true"></i>
                                </a>
                            </li>

                        </ul>
                    </li>
                </ul>
            </nav>

            <!-- Page Content Holder -->
            <div class="container-fluid" id="content">
                <header class="text-center base-header">
                    <div class="row justify-content-end">
                        <div class="col-auto mr-4 white header-social">
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <a href="tel:419-422-5930">
                                        <i class="fa fa-phone fa-sm" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.instagram.com/thegatheringfindlay/" target="_blank">
                                        <i class="fa fa-instagram fa-sm" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.facebook.com/FindlayGathering/" target="_blank">
                                    <i class="fa fa-facebook-f fa-sm" aria-hidden="true"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-1 hamburger pl-5" id="sidebarCollapse">
                            <i class="fa fa-align-justify fa-sm" aria-hidden="true"></i>
                        </div>
                        
                        <div class="col-8 offset-1 main-nav">
                            <div class="row justify-content-between">
                                <div class="col-auto"><a href="{% url 'the_gathering:eat' %}" class="header-nav">Eat</a></div>
                                <div class="col-auto"><a href="{% url 'the_gathering:drink' %}" class="header-nav">Drink</a></div>
                                
                                <div class="col-4">
                                    <a href="{% url 'the_gathering:home' %}" class="logo_text">
                                        <img src="{% static 'images/header_logo_text.png' %}" alt="The Gathering - Fine Food &amp; Spirits">
                                    </a>
                                </div>
                                
                                <div class="col-auto"><a href="{% url 'the_gathering:about' %}" class="header-nav">About</a></div>
                                <div class="col-auto"><a href="{% url 'the_gathering:menus' %}" class="header-nav">Menus</a></div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row justify-content-center">
                        <div class="col-auto">
                            <img class="logo" src="{% static 'images/header_logo.png' %}">
                        </div>    
                    </div>
                            
                </header>

                {% block content %}
                {% endblock %}


                <footer class="text-center base-footer white">
    
                    <div class="row justify-content-center">
                        <div class="col-auto">
                            <img class="logo w-75" src="{% static 'images/header_logo.png' %}">
                        </div>
                    </div>
                        
                    <div class="row justify-content-around my-5">
                        <div class="col-md-3">
                            <h3 class="mb-4">The Anvil</h3>
                            <a href="tel:567-525-3235">
                                <p class="h6 white mb-2">567 525 3235</p>
                            </a>
                            <p class="text-uppercase font-weight-bold">Hours</p>
                            <p>Thurs: 5-11</p>
                            <p>Fri: 5-1</p>
                            <p>Sat: 7-2</p>
                            
                        </div>

                        <div class="col-md-3">
                            <h3 class="mb-4">The Gathering</h3>
                            <a href="tel:419-422-5930">
                                <p class="h6 white mb-2">419 422 5930</p>
                            </a>
                            <p class="text-uppercase font-weight-bold">Hours</p>
                            <p>Mon-Thurs: 11-2 | 5-9</p>
                            <p>Fri: 11-2 | 5-10</p>
                            <p>Sat: 5-10</p>
                        </div>

                        <div class="col-md-3">
                            <h3 class="mb-4">Gathering Wine</h3>
                            <a href="tel:567-525-3235">
                                <p class="h6 white mb-2">567 525 3235</p>
                            </a>
                            <p class="text-uppercase font-weight-bold">Hours</p>
                            <p>Mon-Thurs: 11-2 | 4-9</p>
                            <p>Fri: 11-2 | 4-11</p>
                            <p>Sat: 4-11</p>
                        </div>
                    </div>
                        
                    <div class="row justify-content-center" id="footer-nav-list">
                        <div class="col-12 footer-nav">
                            <ul class="list-inline" >
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:eat' %}">Eat</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:drink' %}">Drink</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:shop' %}">Shop</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:events' %}">Events</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:about' %}">About</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:menus' %}">Menus</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:private_events' %}">Private</a></li>
                                <li class="list-inline-item px-2"><a href="{% url 'the_gathering:reservations' %}">Reservations</a></li>
                            </ul>        
                        </div>
                    </div>
                        
                    <div class="row justify-content-between mb-0">
                        <div class="col-auto m-4">
                            <p class="white">&copy; 2018 The Gathering</p>        
                        </div>

                        <div class="col-auto m-4 footer-social">
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <a href="tel:419-422-5930" class="social">
                                        <i class="fa fa-phonek fa-lg" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.instagram.com/thegatheringfindlay/" class="social" target="_blank">
                                        <i class="fa fa-instagram fa-lg" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.facebook.com/GatheringWineAnvil/" class="social" target="_blank">
                                        <i class="fa fa-facebook fa-lg" aria-hidden="true"></i>
                                    </a>
                                </li>
                            </ul>       
                        </div>
                        
                    </div>
                    
                </footer>


            </div> <!-- End Content -->
        </div><!-- end Wrapper -->

        <div class="overlay"></div>

        <script src="{% static 'js/sr.js' %}"></script>

        <!-- jQuery CDN -->
        <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
        <!-- Bootstrap Js CDN -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <!-- jQuery Custom Scroller CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>